cc_library(
    name = 'queue_manager',
    srcs = ['queue_manager.cpp'],
    hdrs = ['queue_manager.h'],
    deps = [
        '//third_party/queues:queues',
        '//third_party/proto:stack_proto',
        '//vision:vision_queues', 
    ],
    visibility = ['//visibility:public']
)
