cc_library(
  name = 'generator',
  srcs = ['generator.cpp'],
  hdrs = ['generator.h'],
  deps = ['//queue_manager:queue_manager',
          '//vision:vision_queues'],
  visibility = ["//visibility:public"]
)
